### ISSUE TITLE
./configure: "No package 'lxpanel' found"

### ISSUE THREAD

**Issue by p3732** [masami256/backlight-applet#1]
I know you stated the ./configure script does not work and I don't really have insight why this is the case. So here is what I have:
./autogen.sh ran just fine after installing all dependencies (libgtk2.0-dev, build-essential, libglib2.0-dev, intltool, automake, libtool if you start from a fresh lubuntu 13.04 distro)
./configure complains about lxpanel not being installed, which clearly is not the case. Are any dev libraries needed? (Also I commented it out in the configure file, so that it ran just, however make later complained as there where no header files generated...)

OS: lubuntu 13.04 (beta 2), 64 bit, latest packages
Attached the terminal output
EDIT: hmm actually can't attach text files, so here: https://github.com/pe44/various/blob/master/lxpanel.txt

**Comment by masami256** [comment]
Hi.
As a fedora user, I needed to install libXrandr-devel and lxpanel-devel packages to make configure script success. 
So I think you need to have such packages. Unfortunately I don't know these package name in lubuntu.

I paste what files are in the packages. So I hope you can find correct package.
lxpanel-devel(for x86_64 arch) package includes following files.
./usr/include/lxpanel
./usr/include/lxpanel/plugin.h
./usr/lib64/pkgconfig/lxpanel.pc

libXrandr-devel(for x86_64 arch) package includes following files.
./usr/include/X11/extensions/Xrandr.h
./usr/lib64/libXrandr.so
./usr/lib64/pkgconfig/xrandr.pc
./usr/share/man/man3/XRRConfigCurrentConfiguration.3.gz
./usr/share/man/man3/XRRConfigCurrentRate.3.gz
./usr/share/man/man3/XRRConfigRates.3.gz
./usr/share/man/man3/XRRConfigRotations.3.gz
./usr/share/man/man3/XRRConfigSizes.3.gz
./usr/share/man/man3/XRRConfigTimes.3.gz
./usr/share/man/man3/XRRFreeScreenConfigInfo.3.gz
./usr/share/man/man3/XRRGetScreenInfo.3.gz
./usr/share/man/man3/XRRQueryExtension.3.gz
./usr/share/man/man3/XRRQueryVersion.3.gz
./usr/share/man/man3/XRRRootToScreen.3.gz
./usr/share/man/man3/XRRSelectInput.3.gz
./usr/share/man/man3/XRRSetScreenConfig.3.gz
./usr/share/man/man3/XRRSetScreenConfigAndRate.3.gz
./usr/share/man/man3/Xrandr.3.gz

Cheers,

**Comment by p3732** [comment]
Okay, so this really seems to be a packaging problem.
I checked multiple package file lists, but as lxpanel is the only package conserning lxpanel core functionality the packager must have kept the files out. In debian stable/testing/unstable the package lxpanel includes the developer files, but the version is a bit older so I don't want to overwrite it.
This other panel indicator:
https://github.com/danamlund/sensors-lxpanel-plugin
has a description to install it on ubuntu 11.04 and I tried with installing these packages (except for the sensor one) but that didn't help it. I will lurk a bit tomorrow to see in which version the files got lost.
Also I will try to simply extract the files from the debian version and manually copy it over.

**Comment by p3732** [comment]
Okay, so much for "tomorrow". Although I could find packages from Debian that still feature the lxpanel package, I couldn't figure out what to do with them.
Anyway simple workaround for *buntu users: Add this ppa https://launchpad.net/~indicator-brightness/+archive/ppa and install the indicator. Make sure you also have the lxpanel-indicator-plugin. Copypasta:
sudo add-apt-repository ppa:indicator-brightness/ppa
sudo apt-get update
sudo apt-get install lxpanel-indicator-applet-plugin indicator-brightness

This gives you a very basic backlight-indicator thingy that does the job. Screenshots here: http://www.omgubuntu.co.uk/2013/04/brightness-control-ubuntu
